### ISSUE TITLE
Problem with nested loops

### ISSUE THREAD

**Issue by rdebath** [Sanguinarious/brainfuck#1]
This "Hello World!" program fails to run.

```bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```
As does the current Wikipedia one.

**Comment by Sanguinarious** [comment]
Semi-Fixed. Most programs I tested work fine, the one you posted now works, but for some reason wikipedia one doesn't work.

**Comment by rdebath** [comment]
Hmm, yes, nasty little error on [this](https://github.com/Sanguinarious/brainfuck/blob/06173be81eeb3d56bbe243fdca3462dd3118e83c/bf.c#L43) line.

You've incremented your `s` variable without decrementing the remaining length `l` so you get overruns.

**Comment by Sanguinarious** [comment]
Thanks :) Now it seems everything works fine. I guess this is what I get for lets upload all the old random code I could find to GitHub day and I thought that worked.
